### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by luojianxhlxt** [zhongfly/telegram-bot-asf#11]
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnectionPool object at 0x00000213A3066DD8>, 'Connect timed out. (connect timeout=5.0)')': .........................../getUpdates

**Comment by zhongfly** [comment]
网络问题与本项目无关
与telegram连接超时，请自行检查网络以及代理设置，确保能正常连接到telegram。
