### ISSUE TITLE
能否将2fa的验证码加上``

### ISSUE THREAD

**Issue by Mr54233** [zhongfly/telegram-bot-asf#18]
![image](https://user-images.githubusercontent.com/46802509/168099974-14b639c2-5b15-4abb-b96f-3f8c6d69f0b4.png)
使其变成这种点一下就能复制的`验证码`

**Comment by zhongfly** [comment]
需要想办法识别哪些字符是验证码，于是得看看asf里这部分返回的格式是什么

为了防止忘记，暂且记录：
实现时在此位置之后修改 https://github.com/zhongfly/telegram-bot-asf/blob/78c48113061b411bb8ce4913e58929a8d9d09b2c/telegram-asf.py#L270
```python
        bot.editMessageText(
            chat_id=chat_id, message_id=chat_data['msg'], text=res)
        if pattern_2fa.match(command):
            res=re.sub(r'([A-Z0-9]{5}$)',r'`\1`',res)
            bot.editMessageText(
                chat_id=chat_id, message_id=chat_data['msg'], text=res)
            context.job_queue.run_once(mfa_timeout, 15, context=(
                chat_id, chat_data['msg']))
```
匹配2fa命令的正则也应该重写：
```python
pattern_2fa = re.compile(r'.?2fa')
```

**Comment by zhongfly** [comment]
你试试`2fa`分支？我不太方便测试
https://github.com/zhongfly/telegram-bot-asf/tree/2fa

**Comment by Mr54233** [comment]
> 你试试`2fa`分支？我不太方便测试 https://github.com/zhongfly/telegram-bot-asf/tree/2fa

![image](https://user-images.githubusercontent.com/46802509/168190020-87383abe-ca7f-4b47-bbde-5dff1e6dc47d.png)
不知为何tg似乎无法识别机器人发来的``

**Comment by zhongfly** [comment]
> > 你试试`2fa`分支？我不太方便测试 https://github.com/zhongfly/telegram-bot-asf/tree/2fa
> 
> ![image](https://user-images.githubusercontent.com/46802509/168190020-87383abe-ca7f-4b47-bbde-5dff1e6dc47d.png) 不知为何tg似乎无法识别机器人发来的``

估计是我代码里应该设置文本样式为markdown，我之后再看看，我也很久没用这个了

**Comment by zhongfly** [comment]
应该已被 https://github.com/zhongfly/telegram-bot-asf/commit/c94be3d1f461f8035ba7452d94e9183b6567e982 修复

**Comment by Mr54233** [comment]
`2022-05-13 09:17:31,658 - __main__ - INFO - 执行命令：2fa
结果为：<54> 两步验证令牌: HGCW7
2022-05-13 09:17:31,926 - __main__ - WARNING - Update "{'update_id': abcd, 'message': {'date': abcd, 'channel_chat_created': False, 'chat': {'last_name': 'abcd', 'username': 'abcd', 'type': 'private', 'first_name': 'abcd', 'id': abcd}, 'message_id': abcd, 'entities': [], 'delete_chat_photo': False, 'caption_entities': [], 'new_chat_members': [], 'photo': [], 'text': '2fa', 'group_chat_created': False, 'supergroup_chat_created': False, 'new_chat_photo': [], 'from': {'last_name': 'abcd', 'is_bot': False, 'username': 'abcd', 'id': abcd, 'first_name': 'abcd', 'language_code': 'zh-hans'}}}" caused error "Can't parse entities: character '>' is reserved and must be escaped with the preceding '\'"`

问题貌似更大了，甚至不会回复了

**Comment by zhongfly** [comment]
> `2022-05-13 09:17:31,658 - __main__ - INFO - 执行命令：2fa 结果为：<54> 两步验证令牌: HGCW7 2022-05-13 09:17:31,926 - __main__ - WARNING - Update "{'update_id': abcd, 'message': {'date': abcd, 'channel_chat_created': False, 'chat': {'last_name': 'abcd', 'username': 'abcd', 'type': 'private', 'first_name': 'abcd', 'id': abcd}, 'message_id': abcd, 'entities': [], 'delete_chat_photo': False, 'caption_entities': [], 'new_chat_members': [], 'photo': [], 'text': '2fa', 'group_chat_created': False, 'supergroup_chat_created': False, 'new_chat_photo': [], 'from': {'last_name': 'abcd', 'is_bot': False, 'username': 'abcd', 'id': abcd, 'first_name': 'abcd', 'language_code': 'zh-hans'}}}" caused error "Can't parse entities: character '>' is reserved and must be escaped with the preceding '\'"`
> 
> 问题貌似更大了，甚至不会回复了

因为bot名后的`>`是特殊字符，需要转义…这是我没想到的
试试新的？

**Comment by Mr54233** [comment]
![image](https://user-images.githubusercontent.com/46802509/168196509-6adaeeb2-3fbe-4be8-af9b-b6b32ab7945d.png)
还是不行

**Comment by zhongfly** [comment]
> ![image](https://user-images.githubusercontent.com/46802509/168196509-6adaeeb2-3fbe-4be8-af9b-b6b32ab7945d.png) 还是不行

有点搞不懂tg的格式了……我又改了，我觉得这回真的行了

**Comment by Mr54233** [comment]
这下真的行了，谢谢大佬

**Comment by zhongfly** [comment]
也谢谢你帮忙测试，我目前没有测试环境，也没啥时间搭
