### ISSUE TITLE
是不是可以考虑将配置信息转移到单独的json文件里边

### ISSUE THREAD

**Issue by bhxch** [zhongfly/telegram-bot-asf#4]
这样push和pull代码都会更方便

**Comment by zhongfly** [comment]
近期没有时间，可能过几个月会做相关修改…你们改也可以…总感觉需要大改一遍

Zhe Lee <notifications@github.com> 于 2018年11月12日周一 08:42写道：

**Comment by bhxch** [comment]
不会也是在考研吧，还是说要准备期末考试了。

我最近也没时间了，等拷过去了我会一起帮忙改改的。

**Comment by zhongfly** [comment]
https://github.com/zhongfly/telegram-bot-asf/commit/8192c00e79665050bd9de093733d4911d3734335
