### ISSUE TITLE
addlicense 命令的格式有变更

### ISSUE THREAD

**Issue by bhxch** [zhongfly/telegram-bot-asf#9]
根据 [wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#addlicense-licenses) 所说，addlicense 命令有所改动。

默认会认为输入的是 subid，如果输入的是 appid，需要用 app/*****。

望大佬及时修复。

**Comment by zhongfly** [comment]
你输命令时按照appid的格式输入即可，这不是bot需要做的的

Zhe Lee <notifications@github.com> 于 2019年12月11日周三 08:45写道：

**Comment by zhongfly** [comment]
按键方式的addlicense可能我之后有时间再改吧

**Comment by bhxch** [comment]
手动输入完整的命令也会被提示“appID 或者 subID输入错误，请重新输入”。是不是对 addlicense 的格式进行了检查啊。

**Comment by zhongfly** [comment]
对…这个格式检查我之后删除吧，实在是没时间再做什么修改了…

Zhe Lee <notifications@github.com> 于 2019年12月11日周三 08:53写道：

**Comment by bhxch** [comment]
先忙考试，这都不急。
